package edu.umbc.soc;

import java.net.UnknownHostException;
import java.util.Date;
import java.util.UUID;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import com.mongodb.MongoException;

/**
 * Java + MongoDB Hello world Example
 * 
 */
public class App {
	public static void test(String path,String id) {

		try {

			/**** Connect to MongoDB ****/
			// Since 2.10.0, uses MongoClient
			MongoClient mongo = new MongoClient("localhost", 27017);

			/**** Get database ****/
			// if database doesn't exists, MongoDB will create it for you
			DB db = mongo.getDB("TSAscanData");

			/**** Get collection / table from 'testdb' ****/
			// if collection doesn't exists, MongoDB will create it for you
			DBCollection table = db.getCollection("user");

			/**** Insert ****/
			// create a document to store key and value
			BasicDBObject document = new BasicDBObject();
			Object x;
			document.put("ImageID",id);
			document.put("name", path);
			document.put("result", 1); //xyz?? result generated by model will be here
			

			
			
			//document.put("createdDate", new Date());
			table.insert(document);

			/**** Find and display ****/
			BasicDBObject searchQuery = new BasicDBObject();
			searchQuery.put("ImageID", "name");

			DBCursor cursor = table.find(searchQuery);

			while (cursor.hasNext()) {
				System.out.println(cursor.next());
			}

			/**** Update ****/
			// search document where name="ImageID" and update it with new values
			BasicDBObject query = new BasicDBObject();
			query.put("name", "mkyong");

			BasicDBObject newDocument = new BasicDBObject();
			newDocument.put("name", "mkyong-updated");

			BasicDBObject updateObj = new BasicDBObject();
			updateObj.put("$set", newDocument);

			table.update(query, updateObj);

			/**** Find and display ****/
			BasicDBObject searchQuery2 
				= new BasicDBObject().append("name", "mkyong-updated");

			DBCursor cursor2 = table.find(searchQuery2);

			while (cursor2.hasNext()) {
				System.out.println(cursor2.next());
			}

			/**** Done ****/
			System.out.println("Done");

		} catch (UnknownHostException e) {
			e.printStackTrace();
		} catch (MongoException e) {
			e.printStackTrace();
		}

	}


public static void test_Status(String id) {

	try {

		/**** Connect to MongoDB ****/
		// Since 2.10.0, uses MongoClient
		MongoClient mongo = new MongoClient("localhost", 27017);

		/**** Get database ****/
		// if database doesn't exists, MongoDB will create it for you
		DB db = mongo.getDB("TSAscanData");

		/**** Get collection / table from 'testdb' ****/
		// if collection doesn't exists, MongoDB will create it for you
		DBCollection table = db.getCollection("user");

		/**** Insert ****/
	/**	// create a document to store key and value
		BasicDBObject document = new BasicDBObject();
		Object x;
		document.put("ImageID",id);
		document.put("name", path);
		document.put("result", 1); //xyz?? result generated by model will be here 
		

		
		
		//document.put("createdDate", new Date());
		table.insert(document); **/

		/**** Find and display ****/
		BasicDBObject searchQuery = new BasicDBObject();
		searchQuery.put("ImageID", id);

		DBCursor cursor = table.find(searchQuery);

		while (cursor.hasNext()) {
			System.out.println("X1");

			System.out.println(cursor.next());
			System.out.println("X2");

		}

		/**** Update ****/
	/**	// search document where name="ImageID" and update it with new values
		BasicDBObject query = new BasicDBObject();
		query.put("ImageID", "id");

		BasicDBObject newDocument = new BasicDBObject();
		newDocument.put("name", "mkyong-updated");

		BasicDBObject updateObj = new BasicDBObject();
		updateObj.put("$set", newDocument);

		table.update(query, updateObj);   **/

		/**** Find and display ****/
		BasicDBObject searchQuery2 
			= new BasicDBObject().append("result", "mkyong-updated");

		DBCursor cursor2 = table.find(searchQuery2);

		while (cursor2.hasNext()) {
			System.out.println(cursor2.next());
		}

		/**** Done ****/
		System.out.println("status");
		System.out.println(id);

		

	} catch (UnknownHostException e) {
		e.printStackTrace();
	} catch (MongoException e) {
		e.printStackTrace();
	}

}
public static void Test_updateresult (String id, String result) {

	try {

		/**** Connect to MongoDB ****/
		// Since 2.10.0, uses MongoClient
		MongoClient mongo = new MongoClient("localhost", 27017);

		/**** Get database ****/
		// if database doesn't exists, MongoDB will create it for you
		DB db = mongo.getDB("TSAscanData");

		/**** Get collection / table from 'testdb' ****/
		// if collection doesn't exists, MongoDB will create it for you
		DBCollection table = db.getCollection("user");

		/**** Insert ****/
	/**	// create a document to store key and value
		BasicDBObject document = new BasicDBObject();
		Object x;
		document.put("ImageID",id);
		document.put("name", path);
		document.put("result", 1); //xyz?? result generated by model will be here 
		

		
		
		//document.put("createdDate", new Date());
		table.insert(document); **/

		/**** Find and display ****/
		BasicDBObject searchQuery = new BasicDBObject();
		searchQuery.put("ImageID", id);

		DBCursor cursor = table.find(searchQuery);

		while (cursor.hasNext()) {
			System.out.println(cursor.next());
		}

		/**** Update ****/
		// search document where name="ImageID" and update it with new values
		BasicDBObject query = new BasicDBObject();
		query.put("ImageID", id);

		BasicDBObject newDocument = new BasicDBObject();
		newDocument.put("result", result);

		BasicDBObject updateObj = new BasicDBObject();
		updateObj.put("$set", newDocument);

		table.update(query, updateObj);   

		/**** Find and display ****/
		BasicDBObject searchQuery2 
			= new BasicDBObject().append("result", "result-updated");

		DBCursor cursor2 = table.find(searchQuery2);

		while (cursor2.hasNext()) {
			System.out.println(cursor2.next());
		}

		/**** Done ****/
		System.out.println("Done");
		System.out.println(result);
		System.out.println(id);


		

	} catch (UnknownHostException e) {
		e.printStackTrace();
	} catch (MongoException e) {
		e.printStackTrace();
	}

}

public static boolean Test_Auth (String username, String password) {
	boolean found = false;
	try {

		/**** Connect to MongoDB ****/
		// Since 2.10.0, uses MongoClient
		MongoClient mongo = new MongoClient("localhost", 27017);

		/**** Get database ****/
		// if database doesn't exists, MongoDB will create it for you
		DB db = mongo.getDB("TSAscanData");

		/**** Get collection / table from 'TSAscanDB' ****/
		// if collection doesn't exists, MongoDB will create it for you
		DBCollection table = db.getCollection("login");

		/**** Insert ****/
	/**	// create a document to store key and value
		BasicDBObject document = new BasicDBObject();
		Object x;
		document.put("ImageID",id);
		document.put("name", path);
		document.put("result", 1); //xyz?? result generated by model will be here 
		

		
		
		//document.put("createdDate", new Date());
		table.insert(document); **/

		/**** Find and display username****/
		BasicDBObject searchQuery = new BasicDBObject();
		searchQuery.put("user_name", username);
		searchQuery.put("user_password", password);

		DBCursor cursor = table.find(searchQuery);
		found = cursor.size() > 0;
		
		
		while (cursor.hasNext()) {
			System.out.println(cursor.next());
		}
		BasicDBObject searchQuery1 = new BasicDBObject();
		searchQuery1.put("user_password", password);

		DBCursor cursor1 = table.find(searchQuery1);

		while (cursor1.hasNext()) {
			System.out.println(cursor1.next());
		}
		// search document where name="ImageID" and update it with new values
		/**BasicDBObject query = new BasicDBObject();
		query.put("ImageID", id);

		BasicDBObject newDocument = new BasicDBObject();
		newDocument.put("result", result);

		BasicDBObject updateObj = new BasicDBObject();
		updateObj.put("$set", newDocument);

		table.update(query, updateObj);  **/ 

		BasicDBObject searchQuery2 
			= new BasicDBObject().append("user_name", "username");

		DBCursor cursor2 = table.find(searchQuery2);

		while (cursor2.hasNext()) {
			System.out.println(cursor2.next());
		}
		BasicDBObject searchQuery3 
			= new BasicDBObject().append("user_password", "password");

		DBCursor cursor3 = table.find(searchQuery3);

		while (cursor3.hasNext()) {
			System.out.println(cursor3.next());
		}


		
		System.out.println("Done");
		System.out.println(username);
		System.out.println(password);


		

	} catch (UnknownHostException e) {
		e.printStackTrace();
	} catch (MongoException e) {
		e.printStackTrace();
	}
	return found;
}
/**Reg**/
public static void Test_Reg (String username, String email,String password) {

	try {

		/**** Connect to MongoDB ****/
		// Since 2.10.0, uses MongoClient
		MongoClient mongo = new MongoClient("localhost", 27017);

		/**** Get database ****/
		// if database doesn't exists, MongoDB will create it for you
		DB db = mongo.getDB("TSAscanData");

		/**** Get collection / table from 'login' ****/
		// if collection doesn't exists, MongoDB will create it for you
		DBCollection table = db.getCollection("login");

		/**** Insert ****/
	// create a document to store key and value
		BasicDBObject document = new BasicDBObject();
		Object x;
		document.put("user_name",username);
		document.put("user_email", email);
		document.put("user_password", password); //xyz?? result generated by model will be here 
		

		
		
		//document.put("createdDate", new Date());
		table.insert(document); 

		/**** Find and display ****/
		BasicDBObject searchQuery = new BasicDBObject();
		searchQuery.put("user_name", username);

		DBCursor cursor = table.find(searchQuery);

		while (cursor.hasNext()) {
			System.out.println(cursor.next());
		}

		/**** Find and display ****/
		BasicDBObject searchQuery2 
			= new BasicDBObject().append("user_password", "inserted password");

		DBCursor cursor2 = table.find(searchQuery2);

		while (cursor2.hasNext()) {
			System.out.println(cursor2.next());
		}
		/**** Find and display ****/
		BasicDBObject searchQuery3 
			= new BasicDBObject().append("user_email", "inserted email");

		DBCursor cursor3 = table.find(searchQuery3);

		while (cursor3.hasNext()) {
			System.out.println(cursor3.next());
		}

		/**** Done ****/
		System.out.println("Done");
		System.out.println(username);
		System.out.println(email);
		System.out.println(password);


		

	} catch (UnknownHostException e) {
		e.printStackTrace();
	} catch (MongoException e) {
		e.printStackTrace();
	}

}

}